name: Docker Image CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker
      run: ./build-docker
    - name: Run container
      run: docker run --rm -d --name mitie1 -p 8000:8000 mitie:dev
    - name: Test Running
      run: curl --silent --fail localhost:8080 || exit 1
    - name: Shutdown
      run: docker stop mitie1
